#num: llm0
embed_api_base: "https://openkey.cloud/v1"
embed_api_key: "sk-ZoHEaerJzUWlpKHd2dA99e3cA573472c90Fa12Eb729dE3Ce"
embed_model_name: "text-embedding-3-small"

#num: llm1
#refer_api_base: "https://openkey.cloud/v1"
#refer_api_key: "sk-ZoHEaerJzUWlpKHd2dA99e3cA573472c90Fa12Eb729dE3Ce"
#refer_model_name: "gpt-4.1-mini"

#num: llm2
#refer_api_base: "https://openkey.cloud/v1"
#refer_api_key: "sk-ZoHEaerJzUWlpKHd2dA99e3cA573472c90Fa12Eb729dE3Ce"
#refer_model_name: "grok-3-mini-beta"

#num: llm3
#refer_api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
#refer_api_key: "sk-48b7623a081843f391a35213118b43f9"
#refer_model_name: "deepseek-v3"

#num: llm4
#refer_api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
#refer_api_key: "sk-48b7623a081843f391a35213118b43f9"
#refer_model_name: "qwen-plus-latest"

#num: llm5
#refer_api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
#refer_api_key: "sk-48b7623a081843f391a35213118b43f9"
#refer_model_name: "llama3.1-405b-instruct"

#num: llm6
#refer_api_key: "803bf48f-be7b-432a-ae25-dc27e2cdc427"
#refer_api_base: "https://ark.cn-beijing.volces.com/api/v3"
#refer_model_name: "doubao-1-5-pro-32k-250115"

#num: llm7
#refer_api_key: "sk-8HQHhPGyfQXWXwyIWBeha7GGJsgxbgHRMMpVJx1I2yrQ8RcT"
#refer_api_base: "https://api.moonshot.cn/v1"
#refer_model_name: "moonshot-v1-8k"

#num: llm8
#refer_api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
#refer_api_key: "sk-48b7623a081843f391a35213118b43f9"
#refer_model_name: "llama-4-scout-17b-16e-instruct"

#llm0大模型用于输入prompt的嵌入和，llm1-llm8这8个模型是在出题阶段使用的大模型一共1280道题
#下面加一些额外的大模型用于测试
num: "llm_local_dsr18b"
refer_api_base: "http://localhost:11434/v1"
refer_api_key: "not_needed"
refer_model_name: "deepseek-r1:32b"

temperature: 0.7
max_tokens: 200